#!/bin/bash

FNHS=$(mktemp /tmp/snaprotateXXXXX).hs

# echo Will use filename $FNHS >&2

# echo params are $@ >&2

# echo pos 0 is $0 >&2
# echo dirname of pos 0 is $(dirname $0) >&2
LIBDIR=$(dirname $0)

cat > $FNHS << 32804384892038493284093
import SnapRotate

32804384892038493284093

cat $1 | grep --invert-match '^#!' >> $FNHS

cat >> $FNHS << 32804384892038493284093

main = runLevels policy
32804384892038493284093

shift
runhaskell -i$LIBDIR $FNHS $@
rm $FNHS

